// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://czhltxnpaukjqmtgrgzc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN6aGx0eG5wYXVranFtdGdyZ3pjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njg3NjY2NzEsImV4cCI6MjA4NDM0MjY3MX0.ohIMXYzheed4719DO59IPX1K-Lqg1idTJgGlFvo-YME";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});